### PR TITLE
feat: configurable snippet expansion

### PR DESCRIPTION
**Pull request by haorenW1025**
Make snippet expansion configurable
cc @Shatur95

### CODE REVIEW

**Comment by Shatur95** [comment]
Thanks, works as expected.

But I suggest to not define `)` by default. Because things like `object.)` will be expanded to `object.function(arg));` (will be an extra brace).
But `;` can be defined by default.

**Comment by Shatur95** [comment]
In most IDE's this works in even more smart way.

Let's consider the following example, where `|` is the cursor:

```
string.p|()
```

Will be expanded to:

```
string.push_back(|)
```

But the following:

```
string.s|(arg1)
```

Will be expanded to:

```
string.size()|(arg)
```

But if the function accept arguments it will be expanded to the following:

```
string.split(arg|)
```

I'm not sure if this can be somehow implemented in plugin, but just how it works. So, it try to merge completion with available data.

**Comment by haorenW1025** [comment]
Hmm that'll be too hard to implement on my side, and also I think as a completion engine we shouldn't do too much stuff because we're trying to be lightweight and fast as possible. Complex snippet or IDE like feature should be handle by server via additional text edit or stuff like that.

**Comment by Shatur95** [comment]
@haorenW1025, yes, I absolutely agree with you.

**Pull request merged**
