### PR TITLE
auto tigger signature help window when completedone.

### PR DESCRIPTION
**Pull request by glepnir**
@haorenW1025  Please check.

test

### CODE REVIEW

**Comment by sentriz** [comment]
hey how do you jump to the different prefilled signature? eg. you quickly jumped to `format string` then `a ...interface{}`

**Comment by glepnir** [comment]
I bind `tab` to do that.

**Comment by kuator** [comment]
> hey how do you jump to the different prefilled signature? eg. you quickly jumped to `format string` then `a ...interface{}`

He most probably uses some kind of snippet engine like ultisnips or vsnip. Snippet engines allow you to jump to placeholders, you just need to setup mappings, taken from ulitnips github page: 
```let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"```

**Comment by kuator** [comment]
> I bind `tab` to do that.

Mind if I ask: did you decide to switch from CoC to nvim-lsp? Or are you just experimenting?

**Comment by glepnir** [comment]
I am not using `nvim-lspconfig`，I tried making a lspclient based on neovim's built-in lsp，

**Comment by haorenW1025** [comment]
This actually looks very neat! Thanks for your contribution:)

**Comment by nomasprime** [comment]
@glepnir I recently ran into the nvim-lspconfig issue with TS and read [your comment](https://github.com/neovim/nvim-lspconfig/issues/250#issuecomment-646115014).

Looks like you've switched from coc.nvim to your own implementation, bold move. Why move away from coc.nvim and how's it working out so far?

**Comment by glepnir** [comment]
@nomasprime  Obviously this is not the place to discuss this issue.If you are a front-end programmer. It is unwise to use nvim-lsp. Because there is no useful tsserver package server. As in my previous comment. typescript-lang-server has almost ceased maintenance. For me most of the time I write back-end languages. So I chose to implement based on the built-in lsp. Current experience. It's fast I think it is much faster than coc. I will not receive some timeout warnings. another reason. I prefer to use lua to write some neovim stuff. I have written enough vimscript. .In addition, I had a very pleasant conversation with some neovim maintainers. I can implement some cool things to submit to upstream. So this is great

**Comment by nomasprime** [comment]
@glepnir I didn't know whether to post here or on the other thread. Thank you for the detailed explanation though.

We're thinking along the same lines except I'm writing full stack, so currently, as you said, I'm rather limited to CoC. Ideally, I'd rather use built-in too.

**Pull request merged**
