### PR TITLE
feat: add disable filetype

### PR DESCRIPTION
**Pull request by haorenW1025**
fixes: #155

### CODE REVIEW

**Comment by weilbith** [comment]
I just tested it, but unfortunately it does not work for me. I thought that this might be something special for this Denite filter buffer, since I don't know exactly what magic is happening there (the code-base was a bit awkward therefore). So I tried it with a regular filetype I use with completion (`typescript` here). Same result. I still get completions from the LS, path, snippets, ...

**Comment by haorenW1025** [comment]
Hmm it seems working on my side. I have the setting like this
```vim
let g:completion_disable_filetypes = ["cpp", "lua"]
```
Or you can try deleting the view files and see if it works(`rm ~/.local/share/nvim/view/*`)

**Comment by weilbith** [comment]
Okay now it works for my typescript example. But for some reason does the special `denite-filter` buffer  still get completion...

**Comment by haorenW1025** [comment]
Hmm that's weird...Have you checked the filetype of the denite-filter by `echo &filetype`? If so then I have no idea what went wrong..

**Comment by weilbith** [comment]
Sorry for the long delay :see_no_evil: 
Yes I did that. I also have a filetype plugin for this buffer that is working perfectly fine. Can you reproduce this issue? :thinking:

**Comment by haorenW1025** [comment]
Sorry for the longer delay :( I have been very busy last couple of weeks.
I never used denite before so reproducing should take some time, but I'll try doing that these days!

**Comment by reedts** [comment]
Hey @weilbith @haorenW1025, any news on this PR? Would be a great additional feature imo :)

**Comment by weilbith** [comment]
Sorry, but I'm not using this plugin anymore. So I have no clue.

**Comment by ranjithshegde** [comment]
@haorenW1025 Great to see you back!
I tested this PR by ignoring on filetypes like telescopePrompt and netrw and it works fine! 
Would be great if you merge this if you feel this is ready

**Pull request merged**
