### PR TITLE
Improve trigger completion

### PR DESCRIPTION
**Pull request by tricktux**
By providing a lua alternative to tab and s-tab
This removes unneeded vim code

### CODE REVIEW

**Comment by tricktux** [comment]
@haorenW1025 are there any comments or concerns regarding this PR?

**Comment by haorenW1025** [comment]
Ahh I actually leave a comment above, you might have missed that:[. My concerns are removing functions might break backward compatibility. I think you can just leave those functions and have a deprecated comment on that.

**Comment by tricktux** [comment]
Hi @haorenW1025 

I've addressed concerns, please review and let me know if there are any more comments :smile: 

Thanks!

**Comment by haorenW1025** [comment]
LGTM! Thanks

**Pull request merged**
