### PR TITLE
feat: context aware completion

### PR DESCRIPTION
**Pull request by haorenW1025**
context aware completion inspired by coc.nvim

- [x] basic context aware completion
- [x] current solution doesn't work with vim-vsnip-integ, should explore why
- [x] context aware snippets expansion

a gif to explain what I talking about here
On master:
Peek 2020-06-30 23-25

On this patch:
Peek 2020-06-30 23-23

### CODE REVIEW

**Comment by Shatur95** [comment]
Tested!

It also not works for [completion-buffers](https://github.com/steelsojka/completion-buffers) completion.
Also if use arrows instead of `<C-n>` / `<C-p>` to select an item - it will not work.

**Comment by haorenW1025** [comment]
@Shatur95 Yep that's expected. It only works for lsp now. I'll open up some PRs on those source when it's stable enough. 
Also it seems to be working for me on my side using arrows, I think the problem is the `vim-vsnip-integ` issue that I ran into. If you disable `vim-vsnip-integ` it should work.

**Comment by Shatur95** [comment]
> Also it seems to be working for me on my side using arrows, I think the problem is the vim-vsnip-integ issue that I ran into. If you disable vim-vsnip-integ it should work.

Yes, tested it, you are right.

**Comment by haorenW1025** [comment]
@Shatur95 I think the snippet expansion should be good now. Right now snippets will only be expand whenever you have a blank or simply nothing after your cursor. It's still very basic now but you can try it out (still don't work with `vim-vsnip-integ` though, I will fix that)

**Comment by haorenW1025** [comment]
@Shatur95 Should work with vim-vsnip-integ now.

**Comment by Shatur95** [comment]
Tested a bit, works for me!

**Comment by Shatur95** [comment]
>  Right now snippets will only be expand whenever you have a blank or simply nothing after your cursor.

Will you plan to add support to control this? Or maybe `commitCharacters` can make this behavior a bit more smart?
Usually current behavior is very-very convenient. But let's consider the following example in `C++`:

```cpp
int main()
{
    std::string testString;
    std::vector<bool> containerExamle;
    containerExamle.emplace_back(/* ... */);
}
```

If I want to insert `testString.empty()` to the `containerExamle.emplace_back(/* ... */);` instead of `/* ... */` I will have the following completion: `containerExamle.emplace_back(testString.empty);`, but I would expect the following `containerExamle.emplace_back(testString.empty());` (with braces).

Not a big problem in the current example just add `()`, but such function can have several arguments.
Also there can be a template and after completion will look in the following way: `containerExamle.emplace_back(variant.as<class T>());` instead of `containerExamle.emplace_back(variant.as<std::string>());` (with snippet expansion).

**Comment by haorenW1025** [comment]
Yeah I agree that’ll be a great feature. However that would take some time to implement. I have some completion related refactoring in this PR so I want to merge this first, so right now the snippets expansion is only an acceptable solution. You should keep the issue open and I’ll try to enhance it later:)

**Comment by Shatur95** [comment]
Great idea! Thanks!

**Pull request merged**
