### PR TITLE
try fixing the cache issue

### PR DESCRIPTION
**Pull request by haorenW1025**
I go through possible places and `clearCache()` there, hopefully this fix it...

cc @clason might need your help cause I can't reproduce..

### CODE REVIEW

**Comment by clason** [comment]
Sorry, that doesn't seem to make a difference. 😞

**Comment by haorenW1025** [comment]
Can you give me a gif of you running into this issue? Might give me some ideas of what went wrong.

**Comment by clason** [comment]
Screenshot 2020-07-04 at 19 03 21

And here's without caching:
Screenshot 2020-07-04 at 19 05 37

**Comment by haorenW1025** [comment]
That seems to be very random... I think I'll create some loggers and see if it helps.

**Comment by clason** [comment]
Maybe not so random -- it may be that the server doesn't send the candidates all in one go, because it internally polls different sources (asynchronously; note how many -- albeit not all -- missing candidates come from `cleveref.sty`). What _is_ weird is that I don't have the issue if I completely remove the `matching_strategy_list` option...

**Comment by haorenW1025** [comment]
That's another weird things, `matching_strategy_list` should be default to `['exact']` if you don't specify it... Can you print out the variable to double check?

**Comment by clason** [comment]
Ah, sorry, you're right -- the behavior is indeed the same whether the option isn't there or if it's set to just `['exact']`. However, the behavior is in both cases not correct when caching is enabled, although more expected candidates show up. (So maybe it really is a timing thing.)

**Comment by haorenW1025** [comment]
We'll see. I shamelessly copy `log.lua` from neovim and create some log here. The log file will be at `~/.local/share/nvim/completion.log`. You might need to try it when you enable caching and disable.

**Comment by clason** [comment]
Here's the log with caching and exact matching (corresponding to the third picture): 
[completion.log](https://github.com/nvim-lua/completion-nvim/files/4873553/completion.log)

and here's without caching:
[completion.log](https://github.com/nvim-lua/completion-nvim/files/4873555/completion.log)

**Comment by haorenW1025** [comment]
Sorry but can you do it again? And I'm curious about the log file corresponding to the first pictures.

**Comment by clason** [comment]
Trying again: with caching
[completion.log](https://github.com/nvim-lua/completion-nvim/files/4873576/completion.log)

without caching
[completion.log](https://github.com/nvim-lua/completion-nvim/files/4873579/completion.log)

exact, substr, fuzzy; with caching
[completion.log](https://github.com/nvim-lua/completion-nvim/files/4873588/completion.log)

and without caching
[completion.log](https://github.com/nvim-lua/completion-nvim/files/4873586/completion.log)

**Comment by haorenW1025** [comment]
Actually your concern might be correct. For every log file the items count are at most 50, it seems like texlab restrict the number they send back...so caching won't work great.

**Comment by clason** [comment]
Yes, that seems likely. I guess it's the same as with sorting -- the spec isn't clear whether it's the server or the client that's supposed to be handling the list of candidates... My suggestion would be to include (in the server-specific options PR) a `caching` option that defaults to `true`, so it can be turned off for servers that turn out not to handle that well.

**Comment by haorenW1025** [comment]
One specific solution for this might be only enable caching for a certain length of prefix. So say that we set that to five, the complete items shouldn't be a lot so caching would work fine.

**Comment by haorenW1025** [comment]
Still I should create the option to enable or disable caching though.

**Comment by clason** [comment]
> One specific solution for this might be only enable caching for a certain length of prefix. So say that we set that to five, the complete items shouldn't be a lot so caching would work fine.

Hmm, but would that in fact then still save a lot of time? I wondering if it would be worth it then.

(Although you could combine the options, where `-1` for the number of characters would turn off caching altogether.)

**Comment by hrsh7th** [comment]
Hi, The LSP spec has `CompletionResult.incomplete` flag.
I think the problem relates to it maybe.

**Comment by haorenW1025** [comment]
@hrsh7th Thank for the information! Indeed it seems related, I'll try looking into it:)

**Comment by haorenW1025** [comment]
Okay so I think `texlab` and `sumneko_lua` both doesn't respect the `result.isIncomplete` flag cause they are always true, `rust_analyer` doesn't even have this implemented(the value is nil) . `clangd` seems to have this correct though.

**Comment by clason** [comment]
I'll check with the `texlab` developers (they are usually very good at respecting the specification, but there might be some VS Code particularities that require doing it this way).

In any case, treating the flag seriously and not caching when it is set sounds like the right thing to do (it's always better to sacrifice performance over correctness).

**Comment by haorenW1025** [comment]
@clason Yeah that seems a reasonable approach. I'll add that.  Closing this PR since none of the changes here seem relevant to the issue, also having log seems to make it much easier to debug, I should add that someday.

**Pull request closed without merging**
