### PR TITLE
doc: Mention snippets.nvim support in README

### PR DESCRIPTION
**Pull request by runiq**
Cf. #172, #180.

### CODE REVIEW

**Comment by haorenW1025** [comment]
Thanks!

**Comment by carlitux** [comment]
@runiq using lsp html to test and after snippet completion this is the result

test

not expand well the snippet.

**Comment by runiq** [comment]
@carlitux Could you open a new issue please?

**Comment by carlitux** [comment]
@runiq done https://github.com/nvim-lua/completion-nvim/issues/322 hope all is into the issue

**Pull request merged**
