### PR TITLE
fix: error when inserting multi line string(#149)

### LINKED ISSUE #149: Completion result causing  error when navigating over a completion with a snippet
I hit on this today which I believe used to work previously 🤔, but let's say that I'm going to go through the list of completions returned and one of those completions is a snippet, it seems to put the actual new text in the buffer including the `$0` which ends up not being rendered correctly as you filtering through them, which causes an error in this case. I'll try to demonstrate exactly what I mean.

Given the following small Scala snippet:

```scala
val option: Option[Int] = Some(3)

option matc@@
```

If I look at the completion results at that point while attempting to completion the `match`, there is the following completion item being returned from the server (Metals).

```
...
    {
      "label": "match",
      "kind": 12,
      "detail": "",
      "preselect": true,
      "sortText": "00000",
      "filterText": "match",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 31,
            "character": 6
          },
          "end": {
            "line": 31,
            "character": 7
          }
        },
        "newText": "match {\n\tcase$0\n}"
      },
      "data": {
        "symbol": "local1",
        "target": "file:/Users/ckipp/Documents/scala-workspace/tester/?id\u003droot"
      }
    },
...
```

When you hit on this option, the following is put into the buffer:

```
option match {^@ case Some(value) =>
```

The server then complains since `\u0000` is not valid for it and was sent to the server during the `textDocument/didChange`. Also, you then see the following message in the message window:

```
Error executing vim.schedule lua callback: Vim:E731: using Dictionary as a String
```

I hope this is enough to give you an idea of what may be going on, but if not, don't hesitate to have me dive into something to help. In other clients (coc.nvim), it seems that instead of showing the `newText` here as you are going through the completion items, they just show the `label`, and then when you select it, then it enters the new text. I've also included a gif of what I'm talking about up above down below:

**My testing minimal init.vim**
Here is an `init.vim` to use

```
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
    Plug 'scalameta/nvim-metals'
call plug#end()
lua require'nvim_lsp'.metals.setup{on_attach=require'completion'.on_attach}
au Filetype scala setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
1. I've included an example repo [here](https://github.com/ckipp01/metals-minimal-sbt) for you to use. There is a file in there called `CompletionError.scala` that you can try the above completion on.
2. Install metals via `:LspInstall metals`
3. Open the `build.sbt` at the root and do a `:BuildImport`
4. Once completion go to `CompletionError.scala` and attempt the completion referenced above.

### PR DESCRIPTION
**Pull request by haorenW1025**
fixes #149

### CODE REVIEW

**Comment by pierreglaser** [comment]
@haorenW1025 Thank you for this! This has been popping up for a while on my machine.

While you're working on this, could you precise whether the completion items that this PR will "fix" are understood as snippets, or simply as text? Can snippet-like completion items return by the Language server can have different placeholders with default value can can be navigated using `vim-vsnip`/`vim-vsnip-integ`?

Currently, the completion item this PR fixes are not understood as snippets by on my machine, simply as plain code (e.g I can't use `vim-snip` mappings to navigate between placeholders in select mode.

I guess this discussion is also related to https://github.com/neovim/neovim/pull/12118

Any info would be appreciated :)

**Comment by haorenW1025** [comment]
Hmm I think vim-vsnip works fine in this PR on my side, do you have a step to reproduce?

**Comment by pierreglaser** [comment]
Sure, simply, can you give me one example of snippet that comes from, say `sumneko`, and that *FOR SURE* (e.g, it works on youre machine) be expanded using `completion-nvim` and `vim-vsnip`/`vim-vsnip-integ`? So I can try on my machine. I'd rather do that than give you false negatives.

**Comment by haorenW1025** [comment]
Yeah I use `sumneko`, just try the completion `for`, it works fine on my side.

**Comment by pierreglaser** [comment]
minimal vimrc
```viml
set completeopt=menuone,noinsert,noselect
set shortmess+=c

let g:completion_enable_snippet = 'vim-vsnip'

packadd! completion-nvim
packadd! nvim-lsp

packadd! vim-vsnip
packadd! vim-vsnip-integ

imap <expr> <Tab>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
imap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-jump-next)'      : '<Tab>'

lua << EOF
  local nvim_lsp = require'nvim_lsp'
  local custom_attach = function()
    require'completion'.on_attach()
  end

  nvim_lsp.sumneko_lua.setup{
  on_attach= custom_attach;
  settings = {
    Lua = {
      completion = {
        keywordSnippet = "Enable";
      };
      runtime = {
        version = "LuaJIT";
        };
      diagnostics={
        enable=true,
        globals={
          "vim", "Color", "c", "Group", "g", "s", "describe", "it", "before_each", "after_each"
        },
      },
    },
  };
}
EOF
```

Using the `for .. in` snippet, I get `for key, value in pairs(t) do      end`, but then I cannot hit `<C-j>` to go navigate to `key` in select mode, as I would expect in a snippet. I can try to provide a screen-recording later on tonight.

**Comment by haorenW1025** [comment]
completion
Hmm I've found out that if you enter insert mode and jump it works fine...Not sure what's the cause though. @hrsh7th any thought on this?

**Comment by hrsh7th** [comment]
It was miss configuration.

```
imap <expr> <Tab>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'
imap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-jump-next)'      : '<C-j>'
```
to
```
imap <expr> <Tab>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'
imap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-jump-next)'      : '<C-j>'
smap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-jump-next)'      : '<C-j>'
```

**Comment by pierreglaser** [comment]
> It was miss configuration.

I still cannot enter select mode with those lines @hrsh7th

> Hmm I've found out that if you enter insert mode and jump it works fine...Not sure what's the cause though. @hrsh7th any thought on this?

So you're saying that with my minimal `init.vim` you cannot reproduce my issue?

Also, I use `neovim` master, maybe neovim/neovim#12118 is causing an issue. What version of neovim do you use?

**Comment by hrsh7th** [comment]
My sumneko_lua settings are below.

```
  lua require'nvim_lsp'.sumneko_lua.setup{
  \   capabilities = {
  \     textDocument = {
  \       completion = {
  \         completionItem = {
  \           snippetSupport = true
  \         }
  \       }
  \     }
  \   },
  \ }
```

Could you test with it?

**Comment by pierreglaser** [comment]
Thanks, do you have a minimal init.vim too?

**Comment by hrsh7th** [comment]
OK, I will try with minimal init.vim. Please wait.

**Comment by hrsh7th** [comment]
@pierreglaser Sorry, I couldn't work almost it with minimal init.vim...

Could you tell me the your using language server that can be easy setup.

**Comment by pierreglaser** [comment]
To reproduce, I'm using `sumneko` with the exact same configuration as you, plus the `'compltion'.on_attach()` callback.

The minimal `init.vim` is shared here: https://github.com/nvim-lua/completion-nvim/pull/150#issuecomment-658311834

If you have a minimal configuration that works, please share it so I can try it :)

**Comment by hrsh7th** [comment]
OK, I will provide `vim-language-server`'s minimal configuration (this language server can be easy to setup).

**Comment by pierreglaser** [comment]
@hrsh7th @haorenW1025 My bad, I actually needed to press `<CR>` to confirm the completion suggestion, which expands the snippet. This was unintuitive to me for some reason, partly because it does not match the mapping used by `vim-vsnip`. I think this deserves a note in the `README`. Thanks for helping out.

**Comment by hrsh7th** [comment]
Thank you for your investigation.
It is good to hear!

**Comment by haorenW1025** [comment]
@pierreglaser Okay that's fine:) I'll add a note to README:)

**Comment by haorenW1025** [comment]
This should be fixed in a new commit.

**Pull request closed without merging**
