### PR TITLE
fix: focus jumps into floating signature help (#376)

### LINKED ISSUE #376: Cursor jumps into floating window of function signature help
**My testing minimal init.vim**
```
call plug#begin('~/.vim/bundle')
    Plug 'neovim/nvim-lspconfig'
    Plug 'nvim-lua/completion-nvim'
call plug#end()
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
lua require'lspconfig'.tsserver.setup{on_attach=require'completion'.on_attach}
au Filetype javascript setl omnifunc=v:lua.vim.lsp.omnifunc
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
1. Get the function signature help to pop up by typing some params in a function call site.
2. Sometimes cursor will window jump into the floating window. for me its >50% of the time so it makes function signature help unusable.
3. Can try to brute force trigger by holding `,` or holding delete on a long string of `,`
image

**Expected behavior**
The cursor should not jump into the floating window of the function signature help.

### PR DESCRIPTION
**Pull request by tomcur**
This seems to fix #376.

### CODE REVIEW

**Comment by jarimayenburg** [comment]
Works for me!

**Comment by ranjithshegde** [comment]
tried it on my fork! Works for me too.
Hope this gets merged soon!

**Comment by hood** [comment]
Please somebody merge this. It fixes the issue for me too.

**Comment by pavelshtanko** [comment]
thanks for the fix

**Comment by ranjithshegde** [comment]
@vigoux has been merging almost all the commits from the last few months. But I am sure he is too busy and tired getting nvim 0.5 to ship.

**Comment by haorenW1025** [comment]
LGTM! Sorry for not merging PR recently:(

**Pull request merged**
