### PR TITLE
Add equal=1

### PR DESCRIPTION
**Pull request by hrsh7th**
This PR aims to reduce pum flicker.

By the way, In completion-nvim#master did not get work with vsnip in my environment...
@haorenW1025 do you get to work it?

And I have another fuzzy match algorithm. if you want it, I will send PR.

### CODE REVIEW

**Comment by hrsh7th** [comment]
Sorry, it does not work correctly... I'm closing it for now...

**Comment by haorenW1025** [comment]
Hmm vsnip seems to work fine on my side. Do you mean the LSP expansion part or the snippets part?

**Comment by hrsh7th** [comment]
Yes, I intented snippet expansion.

OK, I setup completion-nvim after a long time so probably I may have overlooked some misconfiguration.

I will try it again!

**Comment by tami5** [comment]
@hrsh7th I added equal=1 and seems to improved the the flickering issue a lot. 

> Sorry, it does not work correctly... I'm closing it for now...
What was not working correctly.

Thanks

**Pull request closed without merging**
